In [1]:
#Elements acessings row/column
# loc and iloc--->location based and index location based

In [2]:
import pandas as pd
df=pd.DataFrame({"name":['pinky','pop','push','puppy'],"roll-numbers":[401,403,405,34],"branch":["cse","ece","eee","civil"]})

In [3]:
df

name  roll-numbers branch
0  pinky           401    cse
1    pop           403    ece
2   push           405    eee
3  puppy            34  civil

In [4]:
import pandas as pd
df=pd.DataFrame({"name":['hat','hut','home'],"number":[5,6,9],"village":["ndl","bpl","kkl"]},index=[1,2,3])

In [5]:
df

name  number village
1   hat       5     ndl
2   hut       6     bpl
3  home       9     kkl

In [6]:
df.loc[3]

name       home
number        9
village     kkl
Name: 3, dtype: object

In [7]:
df.iloc[0]

name       hat
number       5
village    ndl
Name: 1, dtype: object

In [8]:
df.loc[2]["village"]

'bpl'

In [9]:
df.iloc[1]["number"]

6

In [10]:
df

name  number village
1   hat       5     ndl
2   hut       6     bpl
3  home       9     kkl

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3 entries, 1 to 3
Data columns (total 3 columns):
name       3 non-null object
number     3 non-null int64
village    3 non-null object
dtypes: int64(1), object(2)
memory usage: 176.0+ bytes


In [12]:
df.describe()

number
count  3.000000
mean   6.666667
std    2.081666
min    5.000000
25%    5.500000
50%    6.000000
75%    7.500000
max    9.000000

In [13]:
df.count()

name       3
number     3
village    3
dtype: int64

In [14]:
df.dtypes

name       object
number      int64
village    object
dtype: object

In [15]:
df.count(axis='rows')

name       3
number     3
village    3
dtype: int64

In [16]:
df.count(axis=1)   

1    3
2    3
3    3
dtype: int64

In [17]:
df.count(axis=0)  #

name       3
number     3
village    3
dtype: int64

In [18]:
df.count(axis='columns')

1    3
2    3
3    3
dtype: int64

In [19]:
df.set_index(["number"])

name village
number              
5        hat     ndl
6        hut     bpl
9       home     kkl

In [20]:
df.set_index(["name","village"])

number
name village        
hat  ndl           5
hut  bpl           6
home kkl           9

In [21]:
frame=pd.Series([8,9,1,5,"none"])
frame

0       8
1       9
2       1
3       5
4    none
dtype: object

In [22]:
frame.isnull()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [23]:
frame.describe()

count     5
unique    5
top       5
freq      1
dtype: int64

In [24]:
frame.count()

5

In [25]:
import numpy as np
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
x.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [27]:
data=pd.DataFrame(np.arange(12))
data

0
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10
11  11

In [28]:
data=pd.DataFrame(np.arange(12).reshape(4,3))
data

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [29]:
data=pd.DataFrame(np.arange(12).reshape(4,3),columns=['a','b','c'])
data

a   b   c
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [30]:
y=np.arange(20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
y.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [32]:
data=pd.DataFrame(np.arange(16).reshape(4,4),columns=['a','b','c','d'])
data

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [33]:
data.loc[1,'c']=np.NaN

In [34]:
data

a   b     c   d
0   0   1   2.0   3
1   4   5   NaN   7
2   8   9  10.0  11
3  12  13  14.0  15

In [35]:
data.isnull()

a      b      c      d
0  False  False  False  False
1  False  False   True  False
2  False  False  False  False
3  False  False  False  False

In [36]:
data.isnull().sum()

a    0
b    0
c    1
d    0
dtype: int64

In [37]:
df

name  number village
1   hat       5     ndl
2   hut       6     bpl
3  home       9     kkl

In [38]:
df+data

a   b   c   d name  number village
0 NaN NaN NaN NaN  NaN     NaN     NaN
1 NaN NaN NaN NaN  NaN     NaN     NaN
2 NaN NaN NaN NaN  NaN     NaN     NaN
3 NaN NaN NaN NaN  NaN     NaN     NaN

In [39]:
dd=df.add(data)
dd

a   b   c   d name  number village
0 NaN NaN NaN NaN  NaN     NaN     NaN
1 NaN NaN NaN NaN  NaN     NaN     NaN
2 NaN NaN NaN NaN  NaN     NaN     NaN
3 NaN NaN NaN NaN  NaN     NaN     NaN

In [40]:
dd.add(data,fill_value=1)


a     b     c     d name  number village
0   1.0   2.0   3.0   4.0  NaN     NaN     NaN
1   5.0   6.0   NaN   8.0  NaN     NaN     NaN
2   9.0  10.0  11.0  12.0  NaN     NaN     NaN
3  13.0  14.0  15.0  16.0  NaN     NaN     NaN

In [41]:
np.random.randn(2,4)

array([[-1.04939606,  0.32810698, -1.24877273, -0.25237296],
       [-0.12833002,  0.819163  , -0.79087269, -0.24025109]])

In [43]:
np.random.randn(2,4)

array([[ 0.64353995,  0.75572028, -0.74156017,  0.69451178],
       [ 2.32712794,  1.16442232,  0.6627543 , -1.47872445]])

###Creating data frame with random values

In [46]:
r=pd.DataFrame(np.random.randn(3,4))
r


0         1         2         3
0 -0.216055 -0.291864 -0.980949 -1.582588
1  0.031876  1.409817 -1.065187 -0.367419
2 -1.421404  0.300446  0.315281 -0.453528

In [47]:
r=pd.DataFrame(np.random.randn(3,4),index=['a','b','c'],columns=['s1','s2','s3','s4'])
r

s1        s2        s3        s4
a  0.745558 -0.460393 -1.917048 -1.101915
b  1.639258  1.028922  0.105962 -0.827264
c -1.062363 -0.001421  0.314607  1.616173

In [48]:
r.index=['a','b','c']
r

s1        s2        s3        s4
a  0.745558 -0.460393 -1.917048 -1.101915
b  1.639258  1.028922  0.105962 -0.827264
c -1.062363 -0.001421  0.314607  1.616173

In [49]:
r.columns=['s1','s2','s3','s4']
r

s1        s2        s3        s4
a  0.745558 -0.460393 -1.917048 -1.101915
b  1.639258  1.028922  0.105962 -0.827264
c -1.062363 -0.001421  0.314607  1.616173

Reindexing

In [50]:
r1=r.reindex(['c','a','b','d'])
r1

s1        s2        s3        s4
c -1.062363 -0.001421  0.314607  1.616173
a  0.745558 -0.460393 -1.917048 -1.101915
b  1.639258  1.028922  0.105962 -0.827264
d       NaN       NaN       NaN       NaN

In [51]:
r1.isnull()

s1     s2     s3     s4
c  False  False  False  False
a  False  False  False  False
b  False  False  False  False
d   True   True   True   True

In [52]:
r1.isnull().sum()

s1    1
s2    1
s3    1
s4    1
dtype: int64

remove null values

In [54]:
r1.dropna()

s1        s2        s3        s4
c -1.062363 -0.001421  0.314607  1.616173
a  0.745558 -0.460393 -1.917048 -1.101915
b  1.639258  1.028922  0.105962 -0.827264

In [57]:
r1.fillna(4)       #fill a value in null place

s1        s2        s3        s4
c -1.062363 -0.001421  0.314607  1.616173
a  0.745558 -0.460393 -1.917048 -1.101915
b  1.639258  1.028922  0.105962 -0.827264
d  4.000000  4.000000  4.000000  4.000000

fill a value in backward

In [59]:
r1.fillna(method='bfill',axis=0).fillna(1)

s1        s2        s3        s4
c -1.062363 -0.001421  0.314607  1.616173
a  0.745558 -0.460393 -1.917048 -1.101915
b  1.639258  1.028922  0.105962 -0.827264
d  1.000000  1.000000  1.000000  1.000000

Fill a value in forward

In [60]:
r1.fillna(method='ffill',axis=0).fillna(1)

s1        s2        s3        s4
c -1.062363 -0.001421  0.314607  1.616173
a  0.745558 -0.460393 -1.917048 -1.101915
b  1.639258  1.028922  0.105962 -0.827264
d  1.639258  1.028922  0.105962 -0.827264

In [61]:
r1.isna()

s1     s2     s3     s4
c  False  False  False  False
a  False  False  False  False
b  False  False  False  False
d   True   True   True   True

In [62]:
r1.isnull()

s1     s2     s3     s4
c  False  False  False  False
a  False  False  False  False
b  False  False  False  False
d   True   True   True   True

In [63]:
pd.isna(r1['s3'])

c    False
a    False
b    False
d     True
Name: s3, dtype: bool

Data replacing

In [64]:
r1

s1        s2        s3        s4
c -1.062363 -0.001421  0.314607  1.616173
a  0.745558 -0.460393 -1.917048 -1.101915
b  1.639258  1.028922  0.105962 -0.827264
d       NaN       NaN       NaN       NaN

In [65]:
df33=pd.DataFrame({11:[4,5,6],12:[34,5,6],13:[2,5,9]})
df33

11  12  13
0   4  34   2
1   5   5   5
2   6   6   9

In [66]:
df33.replace(2,5555)

11  12    13
0   4  34  5555
1   5   5     5
2   6   6     9

In [67]:
df33.replace([4,9],99999)

11  12     13
0  99999  34      2
1      5   5      5
2      6   6  99999

In [68]:
df33.replace({6:95,5:22})

11  12  13
0   4  34   2
1  22  22  22
2  95  95   9

Index sorting and ranking

In [69]:
r2=r1.reindex(['a','d','b','m'])
r2

s1        s2        s3        s4
a  0.745558 -0.460393 -1.917048 -1.101915
d       NaN       NaN       NaN       NaN
b  1.639258  1.028922  0.105962 -0.827264
m       NaN       NaN       NaN       NaN

In [70]:
r2.sort_index()

s1        s2        s3        s4
a  0.745558 -0.460393 -1.917048 -1.101915
b  1.639258  1.028922  0.105962 -0.827264
d       NaN       NaN       NaN       NaN
m       NaN       NaN       NaN       NaN

In [71]:
r1.columns=['s4','s1','s2','s3']
r1

s4        s1        s2        s3
c -1.062363 -0.001421  0.314607  1.616173
a  0.745558 -0.460393 -1.917048 -1.101915
b  1.639258  1.028922  0.105962 -0.827264
d       NaN       NaN       NaN       NaN

In [72]:
r1.sort_index(axis=1)

s1        s2        s3        s4
c -0.001421  0.314607  1.616173 -1.062363
a -0.460393 -1.917048 -1.101915  0.745558
b  1.028922  0.105962 -0.827264  1.639258
d       NaN       NaN       NaN       NaN

Groupby

In [73]:
animal_df=pd.DataFrame({'name':['dog','cat','cow','dog','cat'],'place':['zoo','koo','ooo','zoo','ooo'],'feature':['s','s','s','p','m']})
animal_df

name place feature
0  dog   zoo       s
1  cat   koo       s
2  cow   ooo       s
3  dog   zoo       p
4  cat   ooo       m

In [74]:
animal_df.groupby('name').sum()

place feature
name                
cat   kooooo      sm
cow      ooo       s
dog   zoozoo      sp

In [75]:
animal_df.groupby('name').count()

place  feature
name                
cat       2        2
cow       1        1
dog       2        2

In [76]:
animal_df.groupby('name').count()

place  feature
name                
cat       2        2
cow       1        1
dog       2        2

In [77]:
animal_df.groupby('feature').sum()

name      place
feature                      
m              cat        ooo
p              dog        zoo
s        dogcatcow  zookooooo

In [79]:
animal_df.groupby('feature').count()

name  place
feature             
m           1      1
p           1      1
s           3      3

Ranking

In [80]:
ani_df=pd.DataFrame({'name':['dog','cat','cow','dog','cat'],'place':['zoo','koo','ooo','zoo','ooo'],'no.of legs':[4,2,4,6,np.nan]})
ani_df

name place  no.of legs
0  dog   zoo         4.0
1  cat   koo         2.0
2  cow   ooo         4.0
3  dog   zoo         6.0
4  cat   ooo         NaN

In [81]:
ani_df["rank1"]=ani_df["no.of legs"].rank()
ani_df

name place  no.of legs  rank1
0  dog   zoo         4.0    2.5
1  cat   koo         2.0    1.0
2  cow   ooo         4.0    2.5
3  dog   zoo         6.0    4.0
4  cat   ooo         NaN    NaN

In [82]:
ani_df["max-rank"]=ani_df["no.of legs"].rank(method="max")
ani_df

name place  no.of legs  rank1  max-rank
0  dog   zoo         4.0    2.5       3.0
1  cat   koo         2.0    1.0       1.0
2  cow   ooo         4.0    2.5       3.0
3  dog   zoo         6.0    4.0       4.0
4  cat   ooo         NaN    NaN       NaN

In [83]:
ani_df["first-rank"]=ani_df["no.of legs"].rank(method="first")
ani_df

name place  no.of legs  rank1  max-rank  first-rank
0  dog   zoo         4.0    2.5       3.0         2.0
1  cat   koo         2.0    1.0       1.0         1.0
2  cow   ooo         4.0    2.5       3.0         3.0
3  dog   zoo         6.0    4.0       4.0         4.0
4  cat   ooo         NaN    NaN       NaN         NaN

In [84]:
ani_df["non-rank"]=ani_df["no.of legs"].rank(na_option="bottom")
ani_df

name place  no.of legs  rank1  max-rank  first-rank  non-rank
0  dog   zoo         4.0    2.5       3.0         2.0       2.5
1  cat   koo         2.0    1.0       1.0         1.0       1.0
2  cow   ooo         4.0    2.5       3.0         3.0       2.5
3  dog   zoo         6.0    4.0       4.0         4.0       4.0
4  cat   ooo         NaN    NaN       NaN         NaN       5.0

In [85]:
ani_df["pct-rank"]=ani_df["no.of legs"].rank(pct=True)     #pictorial
ani_df

name place  no.of legs  rank1  max-rank  first-rank  non-rank  pct-rank
0  dog   zoo         4.0    2.5       3.0         2.0       2.5     0.625
1  cat   koo         2.0    1.0       1.0         1.0       1.0     0.250
2  cow   ooo         4.0    2.5       3.0         3.0       2.5     0.625
3  dog   zoo         6.0    4.0       4.0         4.0       4.0     1.000
4  cat   ooo         NaN    NaN       NaN         NaN       5.0       NaN

categorise

In [86]:
data_frame=pd.DataFrame({'x':[1,2,3,4,5],'y':[6,7,8,9,10]})
data_frame

x   y
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [87]:
data_frame["cc"]=data_frame['y'].astype('category')
data_frame

x   y  cc
0  1   6   6
1  2   7   7
2  3   8   8
3  4   9   9
4  5  10  10

In [88]:
data_frame["cc"]

0     6
1     7
2     8
3     9
4    10
Name: cc, dtype: category
Categories (5, int64): [6, 7, 8, 9, 10]

In [89]:
data_frame["cc"].cat.categories=["good","bad","worst","verybad","verygood"]
data_frame

x   y        cc
0  1   6      good
1  2   7       bad
2  3   8     worst
3  4   9   verybad
4  5  10  verygood

In [90]:
data_frame["cc"]=data_frame["cc"].set_categories=["good","bad","worst","verybad","verygood"]
data_frame

x   y        cc
0  1   6      good
1  2   7       bad
2  3   8     worst
3  4   9   verybad
4  5  10  verygood

In [91]:
data_frame.sort_values('cc')

x   y        cc
1  2   7       bad
0  1   6      good
3  4   9   verybad
4  5  10  verygood
2  3   8     worst

In [92]:
data_frame.groupby("cc").sum()

x   y
cc             
bad       2   7
good      1   6
verybad   4   9
verygood  5  10
worst     3   8

In [93]:
data_frame.groupby("cc").size()

cc
bad         1
good        1
verybad     1
verygood    1
worst       1
dtype: int64

Reading the data

In [94]:
df=pd.read_table("sample.txt")
df

C:\Users\kvsw5\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


a b c d
0  1 2 3 4
1  5 6 7 8
2  9 5 6 4

In [96]:
df=pd.read_table("ex1.csv")
df

C:\Users\kvsw5\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


a,b,c,d,message
0   1,2,3,4,hello
1   5,6,7,8,world
2  9,10,11,12,foo

In [97]:
df=pd.read_table("ex1.csv",sep=',')
df

C:\Users\kvsw5\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.


a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [98]:
df=pd.read_table("ex2.csv")
df

C:\Users\kvsw5\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


1,2,3,4,hello
0   5,6,7,8,world
1  9,10,11,12,foo

In [99]:
df.head(1)

1,2,3,4,hello
0  5,6,7,8,world

In [100]:
df.tail(1)

1,2,3,4,hello
1  9,10,11,12,foo